### ISSUE TITLE
Hilbert(S::PiecewiseSpace,k::Integer)

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SIE.jl#4]
I think this I've worked this out correctly: Hilbert acting on a PiecewiseSpace consisting of JacobiWeight spaces should have the Cauchy rangespaces be Ultraspherical (i.e. the space of the alternate JacobiWeight spaces). In this way:

```julia
sp = ApproxFun.PiecewiseSpace([JacobiWeight(-.5,-.5,Interval([-2.,-.5])),JacobiWeight(-.5,-.5,Interval([.5,2.]))])
H = Hilbert(sp)
domainspace(H)
rangespace(H)
```

can actually instantiate. Is this correct?

**Comment by dlfivefifty** [comment]
I generalized the Piecewise Hilbert code so that it just always does the rangespace of Hilbert.   So for Jacobi Weight it calls Cauchy(::JacobiWeight,::Ultraspherical) but for Laurent it calls Cauchy(::Laurent,::Laurent)

I guess you haven’t added Cauchy(::JacobiWeight,::Ultraspherical) yet?  This should be easy using the formulae from the book, I can add this unless you feel like doing it.

I still have to re-work out the equivalent formulae for logarithmic kernels…but I think real(cauchyintegral(f,z)) gives the answer up to a constant.

**Comment by MikaelSlevinsky** [comment]
I will be away from the computer for the next couple of days, but my short-range plan is this:
- update Extras folder and add overrides for most functions from Base.math in ApproxFun.jl
- go over the sweeping changes you made in last weeks of December
- then look at this and other SIE-related things. I will make sure right Multiplication works for more (i.e. modified) spaces and file issues as they arise. Actually, here is a problem. Suppose we set the following:
```julia
x = Fun(identity)
d = domain(x)
H = Hilbert(d)
B = ldirichlet(d)
```
Then it's possible to solve:
```julia
u = [B,H[w]]\[1.0,Fun(exp)]
```
in the `Ultraspherical` space, but why can't something like:
```juli
u = [B,H]\[1.0,Fun(exp)]
```
return a solution in the `domainspace(H)`?

Cheers!

**Comment by dlfivefifty** [comment]
Sounds good.  I have a Riemann–Hilbert talk in Banff so I’ll work a bit on SIE this next week.  I think I can get Cauchy working a lot faster, and then I can do log singularities.

I’m hoping to do a live demo of the following, which calculates the UL decomposition of an ∞-dimensional block Toeplitz operator.

G=Fun(z->[1 sin(z)*cos(1/z);
    0.1exp(z+1/z) 1],Circle());
C=Cauchy(-1)
V=(I-(G-I)*C)\(G-I)

T=interlace(map(ToeplitzOperator,mat(G)))
L=interlace(map(ToeplitzOperator,mat(inv(I+C*V))))
U=interlace(map(ToeplitzOperator,mat(I+V+C*V)))
U[1:20,1:20]*L[1:20,1:20]-T[1:20,1:20]

**Comment by MikaelSlevinsky** [comment]
I think this is finally figured out, up to a few probably name changes.
